spring:
  application:
    name: module-client

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 #表示eureka client发送心跳给server端的频率，默认为30秒
    health-check-url-path: /actuator/health #健康检查的地址（依赖spring-boot-starter-actuator）
  client:
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: http://localhost:1111/eureka/


# Swagger界面内容配置
swagger:
  title: Mettre框架网关
  description: Mettre框架网关
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: module-client
    url: http://blog.exrick.cn
    email: 1052461392@qq.com