project:
  name: 正式环境

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://139.129.96.32:3306/mettre_frame?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: "123456"
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    #最大连接数
    maxActive: 30
    #最小连接数
    minIdle: 5
    #获取连接的最大等待时间
    maxWait: 10000
    #解决mysql8小时的问题
    validationgQuery: SELECT 'X'
    #空闲连接的检查时间间隔
    timeBetweenEvictionRunsMillis: 60000
    #空闲连接最小空闲时间
    minEvictableIdleTimeMillis: 300000


  redis:
    host: 139.129.96.32
    password:
    max-active: 100
    max-idle: 10
    max-wait: 100000
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 3000


  resources:
    static-locations: file:${spring.img.location}

  img:
    location: /usr/java/upload/


eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 #表示eureka client发送心跳给server端的频率，默认为30秒
    health-check-url-path: /actuator/health #健康检查的地址（依赖spring-boot-starter-actuator）
  client:
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: http://139.129.96.32:1111/eureka/