server:
  port: 8767

spring:
  profiles:
    active: pro

  application:
    name: module-friend

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8


  # token过期时间（分钟）
  tokenExpireTime: 60*24*7
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10


# 打印sql
logging:
  level:
     com.mettre.moduleclient.mapper : debug



# Swagger界面内容配置
swagger:
  title: Mettre框架网关
  description: Mettre框架网关
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: module-friend
    url: http://blog.exrick.cn
    email: 1052461392@qq.com