project:
  name: 测试环境

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mettre_frame?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    #最大连接数
    maxActive: 30
    #最小连接数
    minIdle: 5
    #获取连接的最大等待时间
    maxWait: 10000
    #解决mysql8小时的问题
    validationgQuery: SELECT 'X'
    #空闲连接的检查时间间隔
    timeBetweenEvictionRunsMillis: 60000
    #空闲连接最小空闲时间
    minEvictableIdleTimeMillis: 300000