server:
  port: 8762

spring:
  application:
      name: module-gateway

  profiles:
      active: pro


zuul:
    host:
        max-per-route-connections: 20000
        socket-timeout-millis: 20000
        connect-timeout-millis: 20000

    routes:
          module-client:
                path: /module-client/**
          account:
                path: /account/**

# Swagger界面内容配置
swagger:
  title: Mettre框架网关
  description: Mettre框架网关
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: module-gateway
    url: http://blog.exrick.cn
    email: 1052461392@qq.com
