project:
  name: 正式环境



eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 #表示eureka client发送心跳给server端的频率，默认为30秒
    health-check-url-path: /actuator/health #健康检查的地址（依赖spring-boot-starter-actuator）
  client:
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: http://139.129.96.32:1111/eureka/